/*
Lob

The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

API version: 1.3.0
Contact: lob-openapi@lob.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lob

import (
	"encoding/json"
	
	"time"
)

// CampaignUpdatable struct for CampaignUpdatable
type CampaignUpdatable struct {
	Name *string `json:"name,omitempty"`
	// An internal description that identifies this resource. Must be no longer than 255 characters. 
	Description NullableString `json:"description,omitempty"`
	ScheduleType *CmpScheduleType `json:"schedule_type,omitempty"`
	// If `schedule_type` is `target_delivery_date`, provide a targeted delivery date for mail pieces in this campaign.
	TargetDeliveryDate *time.Time `json:"target_delivery_date,omitempty"`
	// If `schedule_type` is `scheduled_send_date`, provide a date to send this campaign.
	SendDate *time.Time `json:"send_date,omitempty"`
	// A window, in minutes, within which the campaign can be canceled.
	CancelWindowCampaignMinutes *int32 `json:"cancel_window_campaign_minutes,omitempty"`
	// Use metadata to store custom information for tagging and labeling back to your internal systems. Must be an object with up to 20 key-value pairs. Keys must be at most 40 characters and values must be at most 500 characters. Neither can contain the characters `\"` and `\\`. i.e. '{\"customer_id\" : \"NEWYORK2015\"}' Nested objects are not supported.  See [Metadata](#section/Metadata) for more information.
	Metadata *map[string]string `json:"metadata,omitempty"`
	// Whether or not the campaign is still a draft.
	IsDraft *bool `json:"is_draft,omitempty"`
	UseType NullableCmpUseType `json:"use_type,omitempty"`
	// Whether or not a mail piece should be automatically canceled and not sent if the address is updated via NCOA.
	AutoCancelIfNcoa *bool `json:"auto_cancel_if_ncoa,omitempty"`
}

// NewCampaignUpdatable instantiates a new CampaignUpdatable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignUpdatable() *CampaignUpdatable {
	this := CampaignUpdatable{}
	return &this
}

// NewCampaignUpdatableWithDefaults instantiates a new CampaignUpdatable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignUpdatableWithDefaults() *CampaignUpdatable {
	this := CampaignUpdatable{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CampaignUpdatable) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CampaignUpdatable) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CampaignUpdatable) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CampaignUpdatable) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CampaignUpdatable) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CampaignUpdatable) UnsetDescription() {
	o.Description.Unset()
}

// GetScheduleType returns the ScheduleType field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetScheduleType() CmpScheduleType {
	if o == nil || o.ScheduleType == nil {
		var ret CmpScheduleType
		return ret
	}
	return *o.ScheduleType
}

// GetScheduleTypeOk returns a tuple with the ScheduleType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetScheduleTypeOk() (*CmpScheduleType, bool) {
	if o == nil || o.ScheduleType == nil {
		return nil, false
	}
	return o.ScheduleType, true
}

// HasScheduleType returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasScheduleType() bool {
	if o != nil && o.ScheduleType != nil {
		return true
	}

	return false
}

// SetScheduleType gets a reference to the given CmpScheduleType and assigns it to the ScheduleType field.
func (o *CampaignUpdatable) SetScheduleType(v CmpScheduleType) {
	o.ScheduleType = &v
}

// GetTargetDeliveryDate returns the TargetDeliveryDate field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetTargetDeliveryDate() time.Time {
	if o == nil || o.TargetDeliveryDate == nil {
		var ret time.Time
		return ret
	}
	return *o.TargetDeliveryDate
}

// GetTargetDeliveryDateOk returns a tuple with the TargetDeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetTargetDeliveryDateOk() (*time.Time, bool) {
	if o == nil || o.TargetDeliveryDate == nil {
		return nil, false
	}
	return o.TargetDeliveryDate, true
}

// HasTargetDeliveryDate returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasTargetDeliveryDate() bool {
	if o != nil && o.TargetDeliveryDate != nil {
		return true
	}

	return false
}

// SetTargetDeliveryDate gets a reference to the given time.Time and assigns it to the TargetDeliveryDate field.
func (o *CampaignUpdatable) SetTargetDeliveryDate(v time.Time) {
	o.TargetDeliveryDate = &v
}

// GetSendDate returns the SendDate field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetSendDate() time.Time {
	if o == nil || o.SendDate == nil {
		var ret time.Time
		return ret
	}
	return *o.SendDate
}

// GetSendDateOk returns a tuple with the SendDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetSendDateOk() (*time.Time, bool) {
	if o == nil || o.SendDate == nil {
		return nil, false
	}
	return o.SendDate, true
}

// HasSendDate returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasSendDate() bool {
	if o != nil && o.SendDate != nil {
		return true
	}

	return false
}

// SetSendDate gets a reference to the given time.Time and assigns it to the SendDate field.
func (o *CampaignUpdatable) SetSendDate(v time.Time) {
	o.SendDate = &v
}

// GetCancelWindowCampaignMinutes returns the CancelWindowCampaignMinutes field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetCancelWindowCampaignMinutes() int32 {
	if o == nil || o.CancelWindowCampaignMinutes == nil {
		var ret int32
		return ret
	}
	return *o.CancelWindowCampaignMinutes
}

// GetCancelWindowCampaignMinutesOk returns a tuple with the CancelWindowCampaignMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetCancelWindowCampaignMinutesOk() (*int32, bool) {
	if o == nil || o.CancelWindowCampaignMinutes == nil {
		return nil, false
	}
	return o.CancelWindowCampaignMinutes, true
}

// HasCancelWindowCampaignMinutes returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasCancelWindowCampaignMinutes() bool {
	if o != nil && o.CancelWindowCampaignMinutes != nil {
		return true
	}

	return false
}

// SetCancelWindowCampaignMinutes gets a reference to the given int32 and assigns it to the CancelWindowCampaignMinutes field.
func (o *CampaignUpdatable) SetCancelWindowCampaignMinutes(v int32) {
	o.CancelWindowCampaignMinutes = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetMetadata() map[string]string {
	if o == nil || o.Metadata == nil {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CampaignUpdatable) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetIsDraft returns the IsDraft field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetIsDraft() bool {
	if o == nil || o.IsDraft == nil {
		var ret bool
		return ret
	}
	return *o.IsDraft
}

// GetIsDraftOk returns a tuple with the IsDraft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetIsDraftOk() (*bool, bool) {
	if o == nil || o.IsDraft == nil {
		return nil, false
	}
	return o.IsDraft, true
}

// HasIsDraft returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasIsDraft() bool {
	if o != nil && o.IsDraft != nil {
		return true
	}

	return false
}

// SetIsDraft gets a reference to the given bool and assigns it to the IsDraft field.
func (o *CampaignUpdatable) SetIsDraft(v bool) {
	o.IsDraft = &v
}

// GetUseType returns the UseType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CampaignUpdatable) GetUseType() CmpUseType {
	if o == nil || o.UseType.Get() == nil {
		var ret CmpUseType
		return ret
	}
	return *o.UseType.Get()
}

// GetUseTypeOk returns a tuple with the UseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CampaignUpdatable) GetUseTypeOk() (*CmpUseType, bool) {
	if o == nil {
		return nil, false
	}
	return o.UseType.Get(), o.UseType.IsSet()
}

// HasUseType returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasUseType() bool {
	if o != nil && o.UseType.IsSet() {
		return true
	}

	return false
}

// SetUseType gets a reference to the given NullableCmpUseType and assigns it to the UseType field.
func (o *CampaignUpdatable) SetUseType(v CmpUseType) {
	o.UseType.Set(&v)
}
// SetUseTypeNil sets the value for UseType to be an explicit nil
func (o *CampaignUpdatable) SetUseTypeNil() {
	o.UseType.Set(nil)
}

// UnsetUseType ensures that no value is present for UseType, not even an explicit nil
func (o *CampaignUpdatable) UnsetUseType() {
	o.UseType.Unset()
}

// GetAutoCancelIfNcoa returns the AutoCancelIfNcoa field value if set, zero value otherwise.
func (o *CampaignUpdatable) GetAutoCancelIfNcoa() bool {
	if o == nil || o.AutoCancelIfNcoa == nil {
		var ret bool
		return ret
	}
	return *o.AutoCancelIfNcoa
}

// GetAutoCancelIfNcoaOk returns a tuple with the AutoCancelIfNcoa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignUpdatable) GetAutoCancelIfNcoaOk() (*bool, bool) {
	if o == nil || o.AutoCancelIfNcoa == nil {
		return nil, false
	}
	return o.AutoCancelIfNcoa, true
}

// HasAutoCancelIfNcoa returns a boolean if a field has been set.
func (o *CampaignUpdatable) HasAutoCancelIfNcoa() bool {
	if o != nil && o.AutoCancelIfNcoa != nil {
		return true
	}

	return false
}

// SetAutoCancelIfNcoa gets a reference to the given bool and assigns it to the AutoCancelIfNcoa field.
func (o *CampaignUpdatable) SetAutoCancelIfNcoa(v bool) {
	o.AutoCancelIfNcoa = &v
}

func (o CampaignUpdatable) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.ScheduleType != nil {
		toSerialize["schedule_type"] = o.ScheduleType
	}
	if o.TargetDeliveryDate != nil {
		toSerialize["target_delivery_date"] = o.TargetDeliveryDate
	}
	if o.SendDate != nil {
		toSerialize["send_date"] = o.SendDate
	}
	if o.CancelWindowCampaignMinutes != nil {
		toSerialize["cancel_window_campaign_minutes"] = o.CancelWindowCampaignMinutes
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.IsDraft != nil {
		toSerialize["is_draft"] = o.IsDraft
	}
	if o.UseType.IsSet() {
		toSerialize["use_type"] = o.UseType.Get()
	}
	if o.AutoCancelIfNcoa != nil {
		toSerialize["auto_cancel_if_ncoa"] = o.AutoCancelIfNcoa
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignUpdatable struct {
	value *CampaignUpdatable
	isSet bool
}

func (v NullableCampaignUpdatable) Get() *CampaignUpdatable {
	return v.value
}

func (v *NullableCampaignUpdatable) Set(val *CampaignUpdatable) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignUpdatable) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignUpdatable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignUpdatable(val *CampaignUpdatable) *NullableCampaignUpdatable {
	return &NullableCampaignUpdatable{value: val, isSet: true}
}

func (v NullableCampaignUpdatable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignUpdatable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


