/*
Lob

The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

API version: 1.3.0
Contact: lob-openapi@lob.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lob

import (
	"encoding/json"
	
)

// RequiredAddressColumnMapping The mapping of column headers in your file to Lob-required fields for the resource created. See our <a href=\"https://help.lob.com/print-and-mail/building-a-mail-strategy/campaign-or-triggered-sends/campaign-audience-guide#required-columns-2\" target=\"_blank\">Campaign Audience Guide</a> for additional details.
type RequiredAddressColumnMapping struct {
	// The column header from the csv file that should be mapped to the required field `name`
	Name NullableString `json:"name"`
	// The column header from the csv file that should be mapped to the required field `address_line1`
	AddressLine1 NullableString `json:"address_line1"`
	// The column header from the csv file that should be mapped to the required field `address_city`
	AddressCity NullableString `json:"address_city"`
	// The column header from the csv file that should be mapped to the required field `address_state`
	AddressState NullableString `json:"address_state"`
	// The column header from the csv file that should be mapped to the required field `address_zip`
	AddressZip NullableString `json:"address_zip"`
}

// NewRequiredAddressColumnMapping instantiates a new RequiredAddressColumnMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequiredAddressColumnMapping(name NullableString, addressLine1 NullableString, addressCity NullableString, addressState NullableString, addressZip NullableString) *RequiredAddressColumnMapping {
	this := RequiredAddressColumnMapping{}
	this.Name = name
	this.AddressLine1 = addressLine1
	this.AddressCity = addressCity
	this.AddressState = addressState
	this.AddressZip = addressZip
	return &this
}

// NewRequiredAddressColumnMappingWithDefaults instantiates a new RequiredAddressColumnMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequiredAddressColumnMappingWithDefaults() *RequiredAddressColumnMapping {
	this := RequiredAddressColumnMapping{}
	var name string = "null"
	this.Name = *NewNullableString(&name)
	var addressLine1 string = "null"
	this.AddressLine1 = *NewNullableString(&addressLine1)
	var addressCity string = "null"
	this.AddressCity = *NewNullableString(&addressCity)
	var addressState string = "null"
	this.AddressState = *NewNullableString(&addressState)
	var addressZip string = "null"
	this.AddressZip = *NewNullableString(&addressZip)
	return &this
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RequiredAddressColumnMapping) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}

	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequiredAddressColumnMapping) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// SetName sets field value
func (o *RequiredAddressColumnMapping) SetName(v string) {
	o.Name.Set(&v)
}

// GetAddressLine1 returns the AddressLine1 field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RequiredAddressColumnMapping) GetAddressLine1() string {
	if o == nil || o.AddressLine1.Get() == nil {
		var ret string
		return ret
	}

	return *o.AddressLine1.Get()
}

// GetAddressLine1Ok returns a tuple with the AddressLine1 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequiredAddressColumnMapping) GetAddressLine1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AddressLine1.Get(), o.AddressLine1.IsSet()
}

// SetAddressLine1 sets field value
func (o *RequiredAddressColumnMapping) SetAddressLine1(v string) {
	o.AddressLine1.Set(&v)
}

// GetAddressCity returns the AddressCity field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RequiredAddressColumnMapping) GetAddressCity() string {
	if o == nil || o.AddressCity.Get() == nil {
		var ret string
		return ret
	}

	return *o.AddressCity.Get()
}

// GetAddressCityOk returns a tuple with the AddressCity field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequiredAddressColumnMapping) GetAddressCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AddressCity.Get(), o.AddressCity.IsSet()
}

// SetAddressCity sets field value
func (o *RequiredAddressColumnMapping) SetAddressCity(v string) {
	o.AddressCity.Set(&v)
}

// GetAddressState returns the AddressState field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RequiredAddressColumnMapping) GetAddressState() string {
	if o == nil || o.AddressState.Get() == nil {
		var ret string
		return ret
	}

	return *o.AddressState.Get()
}

// GetAddressStateOk returns a tuple with the AddressState field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequiredAddressColumnMapping) GetAddressStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AddressState.Get(), o.AddressState.IsSet()
}

// SetAddressState sets field value
func (o *RequiredAddressColumnMapping) SetAddressState(v string) {
	o.AddressState.Set(&v)
}

// GetAddressZip returns the AddressZip field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RequiredAddressColumnMapping) GetAddressZip() string {
	if o == nil || o.AddressZip.Get() == nil {
		var ret string
		return ret
	}

	return *o.AddressZip.Get()
}

// GetAddressZipOk returns a tuple with the AddressZip field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequiredAddressColumnMapping) GetAddressZipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AddressZip.Get(), o.AddressZip.IsSet()
}

// SetAddressZip sets field value
func (o *RequiredAddressColumnMapping) SetAddressZip(v string) {
	o.AddressZip.Set(&v)
}

func (o RequiredAddressColumnMapping) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name.Get()
	}
	if true {
		toSerialize["address_line1"] = o.AddressLine1.Get()
	}
	if true {
		toSerialize["address_city"] = o.AddressCity.Get()
	}
	if true {
		toSerialize["address_state"] = o.AddressState.Get()
	}
	if true {
		toSerialize["address_zip"] = o.AddressZip.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableRequiredAddressColumnMapping struct {
	value *RequiredAddressColumnMapping
	isSet bool
}

func (v NullableRequiredAddressColumnMapping) Get() *RequiredAddressColumnMapping {
	return v.value
}

func (v *NullableRequiredAddressColumnMapping) Set(val *RequiredAddressColumnMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableRequiredAddressColumnMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableRequiredAddressColumnMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequiredAddressColumnMapping(val *RequiredAddressColumnMapping) *NullableRequiredAddressColumnMapping {
	return &NullableRequiredAddressColumnMapping{value: val, isSet: true}
}

func (v NullableRequiredAddressColumnMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequiredAddressColumnMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


