/*
Lob

The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

API version: 1.3.0
Contact: lob-openapi@lob.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lob

import (
	"encoding/json"
	
)

// CardOrderEditable struct for CardOrderEditable
type CardOrderEditable struct {
	Quantity int32 `json:"quantity"`
}

// NewCardOrderEditable instantiates a new CardOrderEditable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardOrderEditable(quantity int32) *CardOrderEditable {
	this := CardOrderEditable{}
	this.Quantity = quantity
	return &this
}

// NewCardOrderEditableWithDefaults instantiates a new CardOrderEditable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardOrderEditableWithDefaults() *CardOrderEditable {
	this := CardOrderEditable{}
	return &this
}

// GetQuantity returns the Quantity field value
func (o *CardOrderEditable) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *CardOrderEditable) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *CardOrderEditable) SetQuantity(v int32) {
	o.Quantity = v
}

func (o CardOrderEditable) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["quantity"] = o.Quantity
	}
	return json.Marshal(toSerialize)
}

type NullableCardOrderEditable struct {
	value *CardOrderEditable
	isSet bool
}

func (v NullableCardOrderEditable) Get() *CardOrderEditable {
	return v.value
}

func (v *NullableCardOrderEditable) Set(val *CardOrderEditable) {
	v.value = val
	v.isSet = true
}

func (v NullableCardOrderEditable) IsSet() bool {
	return v.isSet
}

func (v *NullableCardOrderEditable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardOrderEditable(val *CardOrderEditable) *NullableCardOrderEditable {
	return &NullableCardOrderEditable{value: val, isSet: true}
}

func (v NullableCardOrderEditable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardOrderEditable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


