/*
Lob

The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

API version: 1.3.0
Contact: lob-openapi@lob.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lob

import (
	"encoding/json"
)

// MultipleComponentsIntl struct for MultipleComponentsIntl
type MultipleComponentsIntl struct {
	// The intended recipient, typically a person's or firm's name.
	Recipient NullableString `json:"recipient,omitempty"`
	// The primary delivery line (usually the street address) of the address. 
	PrimaryLine string `json:"primary_line"`
	// The secondary delivery line of the address. This field is typically empty but may contain information if `primary_line` is too long. 
	SecondaryLine *string `json:"secondary_line,omitempty"`
	City *string `json:"city,omitempty"`
	// The name of the state.
	State *string `json:"state,omitempty"`
	// The postal code.
	PostalCode *string `json:"postal_code,omitempty"`
	Country CountryExtended `json:"country"`
}

// NewMultipleComponentsIntl instantiates a new MultipleComponentsIntl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultipleComponentsIntl(primaryLine string, country CountryExtended) *MultipleComponentsIntl {
	this := MultipleComponentsIntl{}
	this.PrimaryLine = primaryLine
	this.Country = country
	return &this
}

// NewMultipleComponentsIntlWithDefaults instantiates a new MultipleComponentsIntl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultipleComponentsIntlWithDefaults() *MultipleComponentsIntl {
	this := MultipleComponentsIntl{}
	return &this
}

// GetRecipient returns the Recipient field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultipleComponentsIntl) GetRecipient() string {
	if o == nil || o.Recipient.Get() == nil {
		var ret string
		return ret
	}
	return *o.Recipient.Get()
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultipleComponentsIntl) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recipient.Get(), o.Recipient.IsSet()
}

// HasRecipient returns a boolean if a field has been set.
func (o *MultipleComponentsIntl) HasRecipient() bool {
	if o != nil && o.Recipient.IsSet() {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given NullableString and assigns it to the Recipient field.
func (o *MultipleComponentsIntl) SetRecipient(v string) {
	o.Recipient.Set(&v)
}
// SetRecipientNil sets the value for Recipient to be an explicit nil
func (o *MultipleComponentsIntl) SetRecipientNil() {
	o.Recipient.Set(nil)
}

// UnsetRecipient ensures that no value is present for Recipient, not even an explicit nil
func (o *MultipleComponentsIntl) UnsetRecipient() {
	o.Recipient.Unset()
}

// GetPrimaryLine returns the PrimaryLine field value
func (o *MultipleComponentsIntl) GetPrimaryLine() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrimaryLine
}

// GetPrimaryLineOk returns a tuple with the PrimaryLine field value
// and a boolean to check if the value has been set.
func (o *MultipleComponentsIntl) GetPrimaryLineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryLine, true
}

// SetPrimaryLine sets field value
func (o *MultipleComponentsIntl) SetPrimaryLine(v string) {
	o.PrimaryLine = v
}

// GetSecondaryLine returns the SecondaryLine field value if set, zero value otherwise.
func (o *MultipleComponentsIntl) GetSecondaryLine() string {
	if o == nil || o.SecondaryLine == nil {
		var ret string
		return ret
	}
	return *o.SecondaryLine
}

// GetSecondaryLineOk returns a tuple with the SecondaryLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultipleComponentsIntl) GetSecondaryLineOk() (*string, bool) {
	if o == nil || o.SecondaryLine == nil {
		return nil, false
	}
	return o.SecondaryLine, true
}

// HasSecondaryLine returns a boolean if a field has been set.
func (o *MultipleComponentsIntl) HasSecondaryLine() bool {
	if o != nil && o.SecondaryLine != nil {
		return true
	}

	return false
}

// SetSecondaryLine gets a reference to the given string and assigns it to the SecondaryLine field.
func (o *MultipleComponentsIntl) SetSecondaryLine(v string) {
	o.SecondaryLine = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *MultipleComponentsIntl) GetCity() string {
	if o == nil || o.City == nil {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultipleComponentsIntl) GetCityOk() (*string, bool) {
	if o == nil || o.City == nil {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *MultipleComponentsIntl) HasCity() bool {
	if o != nil && o.City != nil {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *MultipleComponentsIntl) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *MultipleComponentsIntl) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultipleComponentsIntl) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *MultipleComponentsIntl) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *MultipleComponentsIntl) SetState(v string) {
	o.State = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *MultipleComponentsIntl) GetPostalCode() string {
	if o == nil || o.PostalCode == nil {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultipleComponentsIntl) GetPostalCodeOk() (*string, bool) {
	if o == nil || o.PostalCode == nil {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *MultipleComponentsIntl) HasPostalCode() bool {
	if o != nil && o.PostalCode != nil {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *MultipleComponentsIntl) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCountry returns the Country field value
func (o *MultipleComponentsIntl) GetCountry() CountryExtended {
	if o == nil {
		var ret CountryExtended
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *MultipleComponentsIntl) GetCountryOk() (*CountryExtended, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *MultipleComponentsIntl) SetCountry(v CountryExtended) {
	o.Country = v
}

func (o MultipleComponentsIntl) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Recipient.IsSet() {
		toSerialize["recipient"] = o.Recipient.Get()
	}
	if true {
		toSerialize["primary_line"] = o.PrimaryLine
	}
	if o.SecondaryLine != nil {
		toSerialize["secondary_line"] = o.SecondaryLine
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.PostalCode != nil {
		toSerialize["postal_code"] = o.PostalCode
	}
	if true {
		toSerialize["country"] = o.Country
	}
	return json.Marshal(toSerialize)
}

type NullableMultipleComponentsIntl struct {
	value *MultipleComponentsIntl
	isSet bool
}

func (v NullableMultipleComponentsIntl) Get() *MultipleComponentsIntl {
	return v.value
}

func (v *NullableMultipleComponentsIntl) Set(val *MultipleComponentsIntl) {
	v.value = val
	v.isSet = true
}

func (v NullableMultipleComponentsIntl) IsSet() bool {
	return v.isSet
}

func (v *NullableMultipleComponentsIntl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultipleComponentsIntl(val *MultipleComponentsIntl) *NullableMultipleComponentsIntl {
	return &NullableMultipleComponentsIntl{value: val, isSet: true}
}

func (v NullableMultipleComponentsIntl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultipleComponentsIntl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


