/*
Lob

The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

API version: 1.3.0
Contact: lob-openapi@lob.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lob.go

import (
	"encoding/json"
)

// TemplateUpdate struct for TemplateUpdate
type TemplateUpdate struct {
	// An internal description that identifies this resource. Must be no longer than 255 characters. 
	Description NullableString `json:"description,omitempty"`
	// Unique identifier prefixed with `vrsn_`.
	PublishedVersion *string `json:"published_version,omitempty"`
}

// NewTemplateUpdate instantiates a new TemplateUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateUpdate() *TemplateUpdate {
	this := TemplateUpdate{}
	return &this
}

// NewTemplateUpdateWithDefaults instantiates a new TemplateUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateUpdateWithDefaults() *TemplateUpdate {
	this := TemplateUpdate{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateUpdate) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *TemplateUpdate) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *TemplateUpdate) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *TemplateUpdate) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *TemplateUpdate) UnsetDescription() {
	o.Description.Unset()
}

// GetPublishedVersion returns the PublishedVersion field value if set, zero value otherwise.
func (o *TemplateUpdate) GetPublishedVersion() string {
	if o == nil || o.PublishedVersion == nil {
		var ret string
		return ret
	}
	return *o.PublishedVersion
}

// GetPublishedVersionOk returns a tuple with the PublishedVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateUpdate) GetPublishedVersionOk() (*string, bool) {
	if o == nil || o.PublishedVersion == nil {
		return nil, false
	}
	return o.PublishedVersion, true
}

// HasPublishedVersion returns a boolean if a field has been set.
func (o *TemplateUpdate) HasPublishedVersion() bool {
	if o != nil && o.PublishedVersion != nil {
		return true
	}

	return false
}

// SetPublishedVersion gets a reference to the given string and assigns it to the PublishedVersion field.
func (o *TemplateUpdate) SetPublishedVersion(v string) {
	o.PublishedVersion = &v
}

func (o TemplateUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.PublishedVersion != nil {
		toSerialize["published_version"] = o.PublishedVersion
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateUpdate struct {
	value *TemplateUpdate
	isSet bool
}

func (v NullableTemplateUpdate) Get() *TemplateUpdate {
	return v.value
}

func (v *NullableTemplateUpdate) Set(val *TemplateUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateUpdate(val *TemplateUpdate) *NullableTemplateUpdate {
	return &NullableTemplateUpdate{value: val, isSet: true}
}

func (v NullableTemplateUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


