/*
Lob

The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 

API version: 1.3.0
Contact: lob-openapi@lob.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lob.go

import (
	"encoding/json"
)

// IntlAutocompletions struct for IntlAutocompletions
type IntlAutocompletions struct {
	// Unique identifier prefixed with `intl_auto_`.
	Id *string `json:"id,omitempty"`
	// An array of objects representing suggested addresses. 
	Suggestions []IntlSuggestions `json:"suggestions,omitempty"`
}

// NewIntlAutocompletions instantiates a new IntlAutocompletions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntlAutocompletions() *IntlAutocompletions {
	this := IntlAutocompletions{}
	return &this
}

// NewIntlAutocompletionsWithDefaults instantiates a new IntlAutocompletions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntlAutocompletionsWithDefaults() *IntlAutocompletions {
	this := IntlAutocompletions{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IntlAutocompletions) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntlAutocompletions) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IntlAutocompletions) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IntlAutocompletions) SetId(v string) {
	o.Id = &v
}

// GetSuggestions returns the Suggestions field value if set, zero value otherwise.
func (o *IntlAutocompletions) GetSuggestions() []IntlSuggestions {
	if o == nil || o.Suggestions == nil {
		var ret []IntlSuggestions
		return ret
	}
	return o.Suggestions
}

// GetSuggestionsOk returns a tuple with the Suggestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntlAutocompletions) GetSuggestionsOk() ([]IntlSuggestions, bool) {
	if o == nil || o.Suggestions == nil {
		return nil, false
	}
	return o.Suggestions, true
}

// HasSuggestions returns a boolean if a field has been set.
func (o *IntlAutocompletions) HasSuggestions() bool {
	if o != nil && o.Suggestions != nil {
		return true
	}

	return false
}

// SetSuggestions gets a reference to the given []IntlSuggestions and assigns it to the Suggestions field.
func (o *IntlAutocompletions) SetSuggestions(v []IntlSuggestions) {
	o.Suggestions = v
}

func (o IntlAutocompletions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Suggestions != nil {
		toSerialize["suggestions"] = o.Suggestions
	}
	return json.Marshal(toSerialize)
}

type NullableIntlAutocompletions struct {
	value *IntlAutocompletions
	isSet bool
}

func (v NullableIntlAutocompletions) Get() *IntlAutocompletions {
	return v.value
}

func (v *NullableIntlAutocompletions) Set(val *IntlAutocompletions) {
	v.value = val
	v.isSet = true
}

func (v NullableIntlAutocompletions) IsSet() bool {
	return v.isSet
}

func (v *NullableIntlAutocompletions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntlAutocompletions(val *IntlAutocompletions) *NullableIntlAutocompletions {
	return &NullableIntlAutocompletions{value: val, isSet: true}
}

func (v NullableIntlAutocompletions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntlAutocompletions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


